export const SELECT_QUESTION = "SELECT_QUESTION";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const GET_ALL_QUESTION_BY_PERSON_ID_REQUEST =
  "GET_ALL_QUESTION_BY_PERSON_ID_REQUEST";
export const GET_ALL_QUESTION_BY_PERSON_ID_SUCCES =
  "GET_ALL_QUESTION_BY_PERSON_ID_SUCCES";
export const GET_ALL_QUESTION_BY_PERSON_ID_ERROR =
  "GET_ALL_QUESTION_BY_PERSON_ID_ERROR";
export const QUESTION_DELETE_REQUEST = "QUESTION_DELETE_REQUEST";
export const SELECT_EDITABLE_QUESTION = "SELECT_EDITABLE_QUESTION";
export const RESET_EDITABLE_QUESTION = "RESET_EDITABLE_QUESTION";
export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const CREATE_QUESTION_REQUEST = "CREATE_QUESTION_REQUEST";

export const SELECT_TOPIC = "SELECT_TOPIC";
export const SET_ALL_TOPIC = "SET_ALL_TOPIC";

export const TOGGLE_SHOW_LEFT_SIDE = "TOGGLE_SHOW_LEFT_SIDE";
export const TOGGLE_SHOW_ADD_QUESTION_AREA = "TOGGLE_SHOW_ADD_QUESTION_AREA";
export const TOGGLE_SHOW_TOPIC = "TOGGLE_SHOW_TOPIC";
export const TOGGLE_SHOW_QUESTION = "TOGGLE_SHOW_QUESTION";
export const TOGGLE_SHOW_REPEAT_QUESTION = "TOGGLE_SHOW_REPEAT_QUESTION";
