export const SELECT_QUESTION = "SELECT_QUESTION";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const ALL_QUESTION_BY_PERSON_ID_REQUEST =
  "ALL_QUESTION_BY_PERSON_ID_REQUEST";
export const ALL_QUESTION_BY_PERSON_ID_SUCCES =
  "ALL_QUESTION_BY_PERSON_ID_SUCCES";
export const ALL_QUESTION_BY_PERSON_ID_ERROR =
  "ALL_QUESTION_BY_PERSON_ID_ERROR";

export const SELECT_TOPIC = "SELECT_TOPIC";
export const SET_ALL_TOPIC = "SET_ALL_TOPIC";

export const TOGGLE_SHOW_LEFT_SIDE = "TOGGLE_SHOW_LEFT_SIDE";
export const TOGGLE_SHOW_ADD_QUESTION_AREA = "TOGGLE_SHOW_ADD_QUESTION_AREA";
export const TOGGLE_SHOW_TOPIC = "TOGGLE_SHOW_TOPIC";
export const TOGGLE_SHOW_QUESTION = "TOGGLE_SHOW_QUESTION";
export const TOGGLE_SHOW_REPEAT_QUESTION = "TOGGLE_SHOW_REPEAT_QUESTION";
